### ISSUE TITLE
  Data path ".path" should match format "path".

### ISSUE THREAD

**Issue by bhaidar** [auth0-blog/pet-adoption-system#1]
Hey @samjulien 
I am getting the below error when I run the schematic. Can you assist? Thanks

````
npm run workspace-schematic -- auth-module auth-adoption --project=adoption-ui
> nx workspace-schematic "auth-module" "auth-adoption" "--project=adoption-ui"

Error: Schematic input does not validate against the Schema: {"project":"adoption-ui","name":"auth-adoption","path":"apps\\adoption-ui\\src\\app\\auth-adoption\\services"}
Errors:

  Data path ".path" should match format "path".
    at MapSubscriber.registry.compile.pipe.operators_1.map.result [as project] (...\node_modules\@angular-devkit\schematics\tools\schema-option-transform.js:31:27)
    at MapSubscriber._next (...\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (...\node_modules\rxjs\internal\Subscriber.js:67:18)
    at TapSubscriber._next (...\node_modules\rxjs\internal\operators\tap.js:65:26)
    at TapSubscriber.Subscriber.next (...\node_modules\rxjs\internal\Subscriber.js:67:18)
    at TakeSubscriber._next (...\node_modules\rxjs\internal\operators\take.js:54:30)
    at TakeSubscriber.Subscriber.next (...\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (...\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (...\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (...\node_modules\rxjs\internal\Subscriber.js:67:18)
````

**Comment by samjulien** [comment]
Can you please provide me the output of `ng version` as well as the version of @nrwl/schematics is in your `package.json`?

Thanks!

**Comment by bhaidar** [comment]
Thanks for getting back to me :-) 


````
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.1.0
Node: 10.14.1
OS: win32 x64
Angular: 7.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.0
@angular-devkit/build-angular      0.11.0
@angular-devkit/build-ng-packagr   0.11.0
@angular-devkit/build-optimizer    0.11.0
@angular-devkit/core               7.1.0
@angular-devkit/schematics         7.1.0
@angular/cdk                       7.1.0
@angular/cli                       7.1.0
@angular/flex-layout               7.0.0-beta.19
@angular/material                  7.1.0
@angular/material-moment-adapter   7.1.0
@ngtools/json-schema               1.1.0
@schematics/angular                7.1.0
@schematics/update                 0.11.0
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.26.1
```

AND

"@nrwl/schematics": "7.4.1",

**Comment by samjulien** [comment]
Hmm, even when I update all of the dependencies I am still not getting this error. What operating system are you on?
